architectury {
    common rootProject.enabled_platforms.split(',')
}

dependencies {
    modImplementation "dev.architectury:architectury:$rootProject.architectury_api_version"
    modCompileOnly "com.cobblemon:mod:$rootProject.cobblemon_version"
    implementation "com.github.twitch4j:twitch4j:$rootProject.twitch4j_version"
}

processResources {
    from(rootProject.file('src/main/resources/assets/cobblemon_streamer_mode/icon.png')) {
        into 'assets/cobblemon_streamer_mode'
    }
}
