modLoader = "javafml"
loaderVersion = "[4,)"
license = "LGPLv3"

[[mods]]
modId = "cobblemon_streamer_mode"
version = "${version}"
displayName = "Cobblemon Streamer Mode"
authors = "ludwici"
description = '''
Twitch viewer voting for Cobblemon battles.
'''
logoFile = "icon.png"

[[dependencies.cobblemon_streamer_mode]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobblemon_streamer_mode]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.21.2)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobblemon_streamer_mode]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.cobblemon_streamer_mode]]
modId = "cobblemon"
type = "required"
versionRange = "[1.7.3,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "cobblemon_streamer_mode.client.mixins.json"
